export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROOM_USER_REPOSITORY = 'ROOM_USER_REPOSITORY';
export const ROOM_REPOSITORY = 'ROOM_REPOSITORY';
export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';
